name       : kcolorchooser
version    : 23.04.2
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kcolorchooser-23.04.2.tar.xz : a3762aabd5b29fc9b9637856ed717717f4bddc6588268b4e91e74f71b7e5529f
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Fix appstream processing
    rm -fr $installdir/usr/share/icons/hicolor/16x16 # actually 18x18
    install -Dm00644 $workdir/logo.png $installdir/usr/share/pixmaps/kcolorchooser.png
