name       : kcolorchooser
version    : 21.12.1
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/kcolorchooser-21.12.1.tar.xz : a3b34c3fe699435664f99a5fad7960f7b38147ecd17010faafd3d03e49cabeb2
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
