name       : kcolorchooser
version    : 19.12.3
release    : 19
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/kcolorchooser-19.12.3.tar.xz : cb0395c1b4f953fd51129cfe5088702ec261f84cc045f889e22c13e81793744a
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
