name       : kcolorchooser
version    : 21.08.2
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kcolorchooser-21.08.2.tar.xz : 4824d09ca5126a151d4836cc01eaa10fa351e1ec2680f6878da0651600107603
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
