name       : kcolorchooser
version    : 21.12.3
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kcolorchooser-21.12.3.tar.xz : fadc3df8e6b47de72681434ecc9370a92fc23cf2aa97c4988b60f524155fd64a
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
