name       : kcolorchooser
version    : 20.08.0
release    : 24
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/kcolorchooser-20.08.0.tar.xz : df1bfd346bfcdea7a585f489f62ab2f76993ce07f83c47cb8202be981b8a3829
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
