name       : kcolorchooser
version    : 23.04.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kcolorchooser-23.04.1.tar.xz : ff9a3f68a381fb3dd12df98ea48144f9c6abbf962c434fb93f0bdcba0b49f329
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
