name       : kcolorchooser
version    : 21.08.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.1/src/kcolorchooser-21.08.1.tar.xz : 0716f37d7e673db16e891e22acfb059f7f7eb0a15fab3f96dcd47519f5f4ed8f
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
