name       : kcolorchooser
version    : 23.04.3
release    : 54
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kcolorchooser-23.04.3.tar.xz : 9853019c4ad78cb5f2202e447d7350916a20d161c92b169fe5999c4885dd37e6
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Fix appstream processing
    rm -fr $installdir/usr/share/icons/hicolor/16x16 # actually 18x18
    install -Dm00644 $workdir/logo.png $installdir/usr/share/pixmaps/kcolorchooser.png
