name       : kcolorchooser
version    : 19.08.3
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kcolorchooser-19.08.3.tar.xz : 0c3d45ceb9029f0d316e61b3f403838b4c7de82a3211a231b539e6755386c657
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
