name       : kcolorchooser
version    : 22.04.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kcolorchooser-22.04.1.tar.xz : f9e78bca7ce4ce3cd1cc4503542d9c7e6753aee0ba4fa5146a3fe09e4b3e32e9
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
