name       : kcolorchooser
version    : 20.12.0
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kcolorchooser-20.12.0.tar.xz : dedcf2020b98c7edc7945d01ae6b38ac62d27c2e6b4e898c98a2f620fffca7ba
homepage   : https://kde.org/applications/graphics/org.kde.kcolorchooser
license    : MIT
component  : multimedia.graphics
summary    : Color chooser and palette editor
description: |
    KColorChooser is a color palette tool, used to mix colors and create custom color palettes.
    Using the dropper, it can obtain the color of any pixel on the screen.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
